name: generate breakout svg

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  deleteOldRuns:
    name: Delete old workflow runs and artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
        continue-on-error: true

      - name: Delete all artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 0d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  generate-svg:
    name: Generate and commit breakout SVGs
    needs: deleteOldRuns
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs (amend + force push)
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit --amend -m "feat: update breakout SVGs" || echo "No changes to amend"
          git push --force
